[package]
name = "iroh-rpc-client"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
description = "RPC type client for iroh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-stream = "0.3.3"
bytes = "1.1.0"
cid = "0.9.0"
config = "0.13.1"
futures = "0.3.21"
hyper = "0.14.23"
iroh-metrics.workspace = true
iroh-rpc-types.workspace = true
iroh-util.workspace = true
libp2p = { version = "0.50", default-features = false, features = ["gossipsub"] }
quic-rpc = { version = "0.2.2", features = ["http2"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
toml = "0.5.9"
tracing = "0.1.34"

[dev-dependencies]
tokio-stream = { version = "0.1.9", features = ["net"] }
