[package]
name = "iroh-rpc-client"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type client for iroh"
rust-version = "1.63"

[dependencies]

anyhow = "1"
async-stream = "0.3.3"
bytes = "1.1.0"
cid = "0.8.0"
config = "0.13.1"
futures = "0.3.21"
iroh-metrics = { path = "../iroh-metrics", default-features = false }
iroh-util = { path = "../iroh-util" }
libp2p = { version = "0.50", default-features = false, features = ["gossipsub"] }
quic-rpc = { version = "0.1.4" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
toml = "0.5.9"
tracing = "0.1.34"
iroh-rpc-types = { path = "../iroh-rpc-types" }
quinn = { version = "0.9.1" }
rustls = { version = "0.20.7", features = ["dangerous_configuration"] }
rcgen = "0.10.0"

[dev-dependencies]
iroh-rpc-types = { path = "../iroh-rpc-types", features = ["testing"] }
tokio-stream = { version = "0.1.9", features = ["net"] }

[features]
default = []
grpc = ["iroh-metrics/rpc-grpc"]
mem = []
