[package]
name = "iroh-util"
version.workspace = true
edition.workspace = true
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license.workspace = true
repository.workspace = true
description = "Utilities for iroh"
rust-version.workspace = true

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
cid = "0.9"
config = "0.13.1"
ctrlc = "3.2.2"
dirs-next = "2.0.0"
futures = "0.3.21"
humansize = "2.0.0"
rlimit = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.26.5"
thiserror = "1.0"
toml = "0.5.9"
tracing = "0.1.34"

[dev-dependencies]
temp-env = "0.3.1"
testdir = "0.7.0"

[target.'cfg(unix)'.dev-dependencies]
nix = "0.26"
