[package]
name = "iroh-util"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Utilities for iroh"

[dependencies]
ctrlc = "3.2.2"
futures = "0.3.5"
anyhow = "1.0.57"
toml = "0.5.9"
serde = { version = "1.0", features = ["derive"] }
dirs = "4.0.0"
config = "0.13.1"
