[package]
name = "iroh-share"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Sharing files with iroh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait = "0.1.56"
bincode = "1.3.3"
bytes = "1.1.0"
cid = { version = "0.9", features = ["serde-codec"] }
clap = { version = "4.0.9", features = ["derive"] }
futures = "0.3.21"
iroh-metrics.workspace = true
iroh-p2p.workspace = true
iroh-resolver.workspace = true
iroh-rpc-client.workspace = true
iroh-rpc-types.workspace = true
iroh-store.workspace = true
iroh-unixfs.workspace = true
iroh-util.workspace = true
libp2p = { version = "0.50", default-features = false, features = ["gossipsub"] }
multibase = "0.9.1"
rand = "0.8.5"
serde = { version = "1", features = ["derive"] }
tempfile = "3.3.0"
tokio = { version = "1" }
tokio-stream = "0.1.9"
tracing = "0.1.34"
tracing-subscriber = "0.3.14"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
