[workspace]
members = [
  "iroh",
  "iroh-bitswap",
  "iroh-car",
  "iroh-ctl",
  "iroh-rpc-client",
  "iroh-rpc-types",
  "iroh-gateway",
  "iroh-metrics",
  "iroh-p2p",
  "iroh-resolver",
  "iroh-store",
  "iroh-util",
  "stores/*",
  "examples"
]

[patch.crates-io]
# TODO: switch to crates.io once 0.45 is released
libp2p = { git = "https://github.com/libp2p/rust-libp2p", branch = "master" }
