[workspace]
members = [
  "iroh",
  "iroh-bytes",
  "iroh-base",
  "iroh-dns-server",
  "iroh-gossip",
  "iroh-metrics",
  "iroh-net",
  "iroh-sync",
  "iroh-test",
  "iroh-net/bench",
  "iroh-cli"
]
resolver = "2"

[profile.release]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false


[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unused-async = "warn"

[patch.crates-io]
quinn = { path = "../quinn/quinn" }
quinn-proto = { path = "../quinn/quinn-proto" }
quinn-udp = { path = "../quinn/quinn-udp" }
