[workspace]
members = [
  "examples",
  "iroh",
  "iroh-api",
  "iroh-bitswap",
  "iroh-car",
  "iroh-gateway",
  "iroh-localops",
  "iroh-metrics",
  "iroh-one",
  "iroh-p2p",
  "iroh-resolver",
  "iroh-rpc-client",
  "iroh-rpc-types",
  "iroh-share",
  "iroh-store",
  "iroh-util",
  "stores/*",
  "xtask",
]
# even if all crates are set to edition 2021, we still need to force the
# resolver to 2
# https://github.com/gfx-rs/wgpu/issues/2356#issuecomment-1005134986
resolver = "2"

[patch.crates-io]
libp2p = { git = "https://github.com/dignifiedquire/rust-libp2p", branch = "iroh-0-50-1" }
#libp2p = { path = "../rust-libp2p" }

[profile.optimized-release]
inherits = 'release'
lto = true
debug = false
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[profile.docker]
inherits = 'release'
lto = true
debug = false
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false
