[workspace]
members = [
  "iroh",
  "iroh-bytes",
  "iroh-base",
  "iroh-dns-server",
  "iroh-gossip",
  "iroh-metrics",
  "iroh-net",
  "iroh-sync",
  "iroh-test",
  "iroh-net/bench",
  "iroh-cli"
]
resolver = "2"

[profile.release]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false


[workspace.lints.rust]
missing_debug_implementations = "warn"

[workspace.lints.clippy]
unused-async = "warn"

[patch.crates-io]
iroh-quinn = { path = "../quinn/iroh-quinn" }
iroh-quinn-proto = { path = "../quinn/iroh-quinn-proto" }
iroh-quinn-udp = { path = "../quinn/iroh-quinn-udp" }
# quinn = { git = "https://github.com/flub/quinn", branch = "flub/reset-rtt" }
# quinn-proto = { git = "https://github.com/flub/quinn", branch = "flub/reset-rtt" }
# quinn-udp = { git = "https://github.com/flub/quinn", branch = "flub/reset-rtt" }
