[workspace]
members = [
  "iroh",
  "iroh-bytes",
  "iroh-gossip",
  "iroh-metrics",
  "iroh-net",
  "iroh-sync",
  "iroh-test",
  "examples/tracker",
  "iroh-net/bench"
]
resolver = "2"

[profile.release]
debug = true

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false
