[workspace]
members = [
  "iroh",
  "iroh-base",
  "iroh-dns-server",
  "iroh-metrics",
  "iroh-net",
  "iroh-test",
  "iroh-net/bench",
  "iroh-cli",
  "iroh-router",
  "net-tools/netwatch",
  "net-tools/portmapper",
]
resolver = "2"

[profile.release]
debug = true

[profile.dev-ci]
inherits = 'dev'
opt-level = 1

[profile.optimized-release]
inherits = 'release'
debug = false
lto = true
debug-assertions = false
opt-level = 3
panic = 'abort'
incremental = false

[workspace.lints.rust]
missing_debug_implementations = "warn"

# We use this --cfg for documenting the cargo features on which an API
# is available.  To preview this locally use: RUSTFLAGS="--cfg
# iroh_docsrs cargo +nightly doc --all-features".  We use our own
# iroh_docsrs instead of the common docsrs to avoid also enabling this
# feature in any dependencies, because some indirect dependencies
# require a feature enabled when using `--cfg docsrs` which we can not
# do.  To enable for a crate set `#![cfg_attr(iroh_docsrs,
# feature(doc_cfg))]` in the crate.
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(iroh_docsrs)"] }

[workspace.lints.clippy]
unused-async = "warn"

# Temporary fix for dependencies
[patch.crates-io]
iroh-base = { path = "./iroh-base" }
iroh-net = { path = "./iroh-net" }
iroh-metrics = { path = "./iroh-metrics" }
iroh-test = { path = "./iroh-test" }
iroh-router = { path = "./iroh-router" }

iroh-gossip = { git = "https://github.com/n0-computer/iroh-gossip", branch = "main" }
iroh-docs = { git = "https://github.com/n0-computer/iroh-docs", branch = "refactor-extract-rpc" }
iroh-blobs = { git = "https://github.com/n0-computer/iroh-blobs", branch = "main" }
