codecov:
  notify:
    require_ci_to_pass: false
    after_n_builds: 1
comment: false
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true