# Use cargo-make to run tasks here: https://crates.io/crates/cargo-make

[tasks.format]
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Module,group_imports=StdExternalCrate,reorder_imports=true",
]

[tasks.format-check]
# This task is used in CI.  The nightly version needs to be kept in
# sync with the check_fmt job in the ci.yml workflow.
workspace = false
command = "cargo"
args = [
     "fmt",
     "--all",
     "--check",
     "--",
     "--config",
     "unstable_features=true",
     "--config",
     "imports_granularity=Module,group_imports=StdExternalCrate,reorder_imports=true",
]
