# Use cargo-make to run tasks here: https://crates.io/crates/cargo-make

[tasks.format]
workspace = false
toolchain = "nightly"
command = "cargo"
args = [
     "fmt",
     "--all",
     "--",
     "--config",
     "imports_granularity=Module,group_imports=StdExternalCrate",
]

[tasks.format-check]
# This task is used in CI.  The nightly version needs to be kept in
# sync with the check_fmt job in the ci.yml workflow.
workspace = false
toolchain = "nightly-2024-05-02"
command = "cargo"
args = [
     "fmt",
     "--all",
     "--check",
     "--",
     "--config",
     "imports_granularity=Module,group_imports=StdExternalCrate",
]
