[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
private = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.0.9", features = ["derive"] }
clap_mangen = "0.2.2"
iroh = { path = "../iroh" }