[package]
name = "iroh-net"
version = "0.28.1"
edition = "2021"
readme = "README.md"
description = "networking support for iroh"
license = "MIT OR Apache-2.0"
authors = ["dignifiedquire <me@dignifiedquire.com>", "n0 team"]
repository = "https://github.com/n0-computer/iroh"
keywords = ["quic", "networking", "holepunching", "p2p"]

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.76"

[lints]
workspace = true

[dependencies]
anyhow = { version = "1" }
axum = { version = "0.7", optional = true }
backoff = "0.4.0"
base64 = "0.22.1"
bytes = "1.7"
clap = { version = "4", features = ["derive"], optional = true }
der = { version = "0.7", features = ["alloc", "derive"] }
derive_more = { version = "1.0.0", features = [
    "debug",
    "display",
    "from",
    "try_into",
    "deref",
] }
futures-buffered = "0.2.8"
futures-concurrency = "7.6"
futures-lite = "2.5"
futures-sink = "0.3"
futures-util = "0.3"
governor = "0.7.0"
hex = "0.4.3"
hickory-proto = "=0.25.0-alpha.2"
hickory-resolver = "=0.25.0-alpha.2"
hostname = "0.4"
http = "1"
http-body-util = "0.1.0"
hyper = { version = "1", features = ["server", "client", "http1"] }
hyper-util = "0.1.1"
igd-next = { version = "0.15.1", features = ["aio_tokio"] }
iroh-base = { version = "0.28.0", features = ["key"] }
iroh-relay = { version = "0.28", path = "../iroh-relay" }
libc = "0.2.139"
netdev = "0.31.0"
netwatch = { version = "0.1.0", path = "../net-tools/netwatch" }
num_enum = "0.7"
once_cell = "1.18.0"
parking_lot = "0.12.1"
pin-project = "1"
pkarr = { version = "2", default-features = false, features = [
    "async",
    "relay",
] }
portmapper = { version = "0.1.0", path = "../net-tools/portmapper" }
postcard = { version = "1", default-features = false, features = [
    "alloc",
    "use-std",
    "experimental-derive",
] }
quinn = { package = "iroh-quinn", version = "0.12.0" }
quinn-proto = { package = "iroh-quinn-proto", version = "0.12.0" }
quinn-udp = { package = "iroh-quinn-udp", version = "0.5.5" }
rand = "0.8"
rcgen = "0.13"
regex = { version = "1.7.1", optional = true }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
] }
ring = "0.17"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1", features = ["derive", "rc"] }
smallvec = "1.11.1"
socket2 = "0.5.3"
stun-rs = "0.1.5"
surge-ping = "0.8.0"
thiserror = "2"
time = "0.3.20"
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "sync",
    "rt",
    "net",
    "fs",
    "io-std",
    "signal",
    "process",
] }
tokio-rustls = { version = "0.26", default-features = false, features = [
    "logging",
    "ring",
] }
tokio-stream = { version = "0.1.15" }
tokio-tungstenite = "0.24"
tokio-tungstenite-wasm = "0.3"
tokio-util = { version = "0.7", features = ["io-util", "io", "codec", "rt"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
], optional = true }
url = { version = "2.5", features = ["serde"] }
watchable = "1.1.2"
webpki = { package = "rustls-webpki", version = "0.102" }
webpki-roots = "0.26"
x509-parser = "0.16"
z32 = "1.0.3"
net-report = { package = "iroh-net-report", path = "../iroh-net-report", version = "0.28" }

# metrics
iroh-metrics = { version = "0.28.0", default-features = false }
strum = { version = "0.26", features = ["derive"] }

# local-swarm-discovery
swarm-discovery = { version = "0.2.1", optional = true }

# dht_discovery
genawaiter = { version = "0.99", features = ["futures03"], optional = true }

[target.'cfg(all(target_os = "linux", not(target_os = "android")))'.dependencies]
netlink-packet-core = "0.7.0"
netlink-packet-route = "0.21"
netlink-sys = "0.8.6"
rtnetlink = "=0.14.1" # pinned because of https://github.com/rust-netlink/rtnetlink/issues/83

[target.'cfg(target_os = "android")'.dependencies]
netlink-packet-core = "0.7.0"
netlink-packet-route = "0.19" # 0.20/21 is blocked on rtnetlink bumping its dependency
netlink-sys = "0.8.6"
rtnetlink = "=0.13.1" # pinned because of https://github.com/rust-netlink/rtnetlink/issues/83

[target.'cfg(target_os = "windows")'.dependencies]
wmi = "0.14"
windows = { version = "0.58", features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_Foundation",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
] }

[dev-dependencies]
axum = { version = "0.7" }
clap = { version = "4", features = ["derive"] }
criterion = "0.5.1"
crypto_box = { version = "0.9.1", features = ["serde", "chacha20"] }
pretty_assertions = "1.4"
rand_chacha = "0.3.1"
tokio = { version = "1", features = [
    "io-util",
    "sync",
    "rt",
    "net",
    "fs",
    "macros",
    "time",
    "test-util",
] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
iroh-test = "0.28.0"
iroh-net = { path = "." }
serde_json = "1"
testresult = "0.4.0"
iroh-relay = { version = "0.28", path = "../iroh-relay", features = ["test-utils", "server"] }

[[bench]]
name = "key"
harness = false

[build-dependencies]
duct = "0.13.6"

[features]
default = ["metrics", "discovery-pkarr-dht"]
metrics = ["iroh-metrics/metrics"]
test-utils = ["iroh-relay/test-utils", "iroh-relay/server", "dep:axum"]
discovery-local-network = ["dep:swarm-discovery"]
discovery-pkarr-dht = ["pkarr/dht", "dep:genawaiter"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "iroh_docsrs"]

[[example]]
name = "listen"

[[example]]
name = "connect"

[[example]]
name = "listen-unreliable"

[[example]]
name = "connect-unreliable"

[[example]]
name = "dht_discovery"
required-features = ["discovery-pkarr-dht"]

[[example]]
name = "locally-discovered-nodes"
required-features = ["discovery-local-network"]
