[package]
name = "iroh-qrpc-types"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type definitions for iroh"
rust-version = "1.63"

[dependencies]
anyhow = "1"
bytes = { version = "1.3.0", features = ["serde"] }
cid = { version = "0.8.6", features = ["serde-codec"] }
derive_more = "0.99.17"
futures = "0.3.24"
hyper = "0.14.23"
multiaddr = "0.16.0"
quic-rpc = { version = "0.1.9", default-features = false }
serde = { version = "1" }
serde-error = "0.1.2"
serde_with = "2.0.0"
tokio = { version = "1", default-features = false }

[features]
default = []

# Builds and empty tonic server & client as well as associated protobufs
# that can be used for testing
testing = []
