[package]
name = "iroh-rpc-types"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type definitions for iroh"


[dependencies]
prost = "0.10.3"
prost-types = "0.10.1"
async-trait = "0.1.56"
anyhow = "1.0.58"
serde_with = "2.0.0"
iroh-metrics = { path = "../iroh-metrics" }

tonic = { version = "0.7.2", optional = true }
tonic-health = { version = "0.6.0", optional = true }

[build-dependencies]
prost-build = "0.10.3"
tonic-build = { version = "0.7.2", features = ["prost"], optional = true }

[features]
default = ["grpc", "mem"]
# GRPC based transport
grpc = ["tonic", "tonic-build", "tonic-health"]
# Memory based transport
mem = []

# Builds and empty tonic server & client as well as associated protobufs
# that can be used for testing
testing = []
