[package]
name = "iroh-rpc-types"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
description = "RPC type definitions for iroh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bytes = { version = "1.3.0", features = ["serde"] }
cid = { version = "0.9", features = ["serde-codec"] }
derive_more = "0.99.17"
futures = "0.3.24"
libp2p = { version = "0.50", default-features = false, features = ["serde"] }
quic-rpc = { version = "0.2.2", default-features = false }
serde = { version = "1" }
serde-error = "0.1.2"
serde_with = "2.1.0"
tokio = { version = "1", default-features = false }
