[package]
name = "iroh-net-bench"
version = "0.27.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.22"
bytes = "1.7"
hdrhistogram = { version = "7.2", default-features = false }
iroh-net = { path = ".." }
iroh-metrics = { path = "../../iroh-metrics" }
quinn = { package = "iroh-quinn", version = "0.11" }
rcgen = "0.12"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.0.1", features = ["rt", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "ansi", "time", "local-time"] }
socket2 = "0.5"
futures-lite = "2.3.0"

[features]
default = []
local-relay = ["iroh-net/test-utils"]
