[package]
name = "flatfs-store"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Implementation of FlatFS"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
backoff = "0.4.0"
ignore = "0.4.18"

[dev-dependencies]
tempfile = "3.3.0"
