[package]
name = "flatfs-store"
version = "0.1.2"
edition.workspace = true
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license.workspace = true
repository.workspace = true
description = "Implementation of FlatFS"
rust-version.workspace = true
publish = false

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
backoff = "0.4.0"
ignore = "0.4.18"

[dev-dependencies]
tempfile = "3.3.0"
