[package]
name = "iroh-example-importer"
publish = false
version = "0.1.3"
edition = "2021"
authors = ["team@n0.computer"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bytes = "1.1"
bytesize = "1.1.0"
clap = { version = "4.0.9", features = ["derive"] }
futures = "0.3.21"
indicatif = "0.17.1"
iroh-car = { path = "../../iroh-car" }
iroh-unixfs = { path = "../../iroh-unixfs" }
iroh-resolver = { path = "../../iroh-resolver" }
iroh-rpc-client = { path = "../../iroh-rpc-client" }
iroh-util = { path = "../../iroh-util" }
par-stream = { version = "0.10.2", default-features = false, features = ["runtime-tokio"]}
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
