[package]
name = "iroh-example-importer"
authors = ["team@n0.computer"]
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
bytesize.workspace = true
clap = { workspace = true, features = ["derive"] }
futures.workspace = true
indicatif.workspace = true
iroh-car.workspace = true
iroh-unixfs.workspace = true
iroh-resolver.workspace = true
iroh-rpc-client.workspace = true
iroh-util.workspace = true
par-stream = { workspace = true, features = ["runtime-tokio"]}
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
