[package]
name = "iroh-node-util"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh"
keywords = ["quic", "networking", "holepunching", "p2p"]

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.76"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.93"
tokio = "1.41.1"
iroh-net = { path = "../iroh-net" }
tempfile = "3.14.0"
strum = "0.26.3"
nested_enum_utils = "0.1.0"
quic-rpc-derive = "0.15.0"
serde = "1.0.215"
serde-error = "0.1.3"
quic-rpc = "0.15.0"
futures-lite = "2.5.0"
tracing = "0.1.40"
