[package]
name = "iroh-localops"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[dependencies]
anyhow = "1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.25", features = ["signal", "process"]}