[package]
name = "iroh"
version = "0.4.1"
edition = "2021"
readme = "README.md"
description = "IPFS reimagined"
license = "MIT/Apache-2.0"
authors = ["dignifiedquire <me@dignifiedquire.com>", "n0 team"]
repository = "https://github.com/n0-computer/iroh"
default-run = "iroh"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.65"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bao-tree = { version = "0.5.0-rc.1", features = ["tokio_fsm"], default-features = false }
derive_more = { version = "0.99.17", git = "https://github.com/JelteF/derive_more", features = ["debug", "display", "from", "try_into"] }
flume = "0.10.14"
futures = "0.3.25"
iroh-io = { version = "0.2.0-rc.1" }
iroh-net = { path = "../iroh-net" }
iroh-bytes = { path = "../iroh-bytes" }
iroh-metrics = { path = "../iroh-metrics", optional = true }
quic-rpc = { version = "0.6", default-features = false, features = ["flume-transport"] }
quinn = "0.10"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["io-util", "rt"] }
tokio-util = { version = "0.7", features = ["io-util", "io"] }
tokio-stream = "0.1"
tracing = "0.1"
paste = { version = "1.0.12", optional = true }
prometheus-client = { version = "0.21.0", optional = true }

# CLI
clap = { version = "4", features = ["derive"], optional = true }
config = { version = "0.13.1", default-features = false, features = ["toml", "preserve_order"], optional = true }
console = { version = "0.15.5", optional = true }
dirs-next = { version = "2.0.0", optional = true }
hex = { version = "0.4.3", optional = true }
indicatif = { version = "0.17", features = ["tokio"], optional = true }
multibase = { version = "0.9.1", optional = true }
num_cpus = { version = "1.15.0", optional = true }
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"], optional = true }
range-collections = { version = "0.4.0", optional = true }
tempfile = { version = "3.4", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }


[features]
default = ["cli", "metrics"]
cli = ["clap", "config", "console", "dirs-next", "hex", "indicatif", "multibase", "num_cpus", "postcard", "quic-rpc/quinn-transport", "range-collections", "tempfile", "tokio/rt-multi-thread", "tracing-subscriber"]
metrics = ["iroh-metrics", "paste", "prometheus-client"]
test = []

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
blake3 = "1.3.3"
bytes = "1"
duct = "0.13.6"
nix = "0.26.2"
rand = "0.8"
regex = { version = "1.7.1", features = ["std"] }
testdir = "0.8"
tokio = { version = "1", features = ["macros", "io-util", "rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"
iroh-io = { version = "0.2.0-rc.1" }

[[bin]]
name = "iroh"
required-features = ["cli"]

