[package]
name = "iroh"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0/MIT"
readme = "README.md"
description = "comming soon"

[dependencies]
cid = "0.8.5"
iroh-resolver = { path = "../iroh-resolver" }
iroh-rpc-types = { path = "../iroh-rpc-types" }
iroh-rpc-client = { path = "../iroh-rpc-client" }
anyhow = "1"
async-trait = "0.1.53"
tokio = { version = "1" }
bytes = "1.1.0"
libp2p = "0.48"
clap = { version = "3.1.14", features = ["derive"] }

[dev-dependencies]
tempfile = "3.3.0"
trycmd = "0.13.6"

[[bin]]
bench = false
path = "src/main.rs"
name = "iroh-ctl"
