[package]
name = "iroh"
version = "0.5.1"
edition = "2021"
readme = "README.md"
description = "Bytes. Distributed."
license = "MIT OR Apache-2.0"
authors = ["dignifiedquire <me@dignifiedquire.com>", "n0 team"]
repository = "https://github.com/n0-computer/iroh"
default-run = "iroh"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.66"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bao-tree = { version = "0.5.0", features = ["tokio_fsm"], default-features = false }
blake3 = "1.3.3"
bytes = "1"
derive_more = { package = "derive_more_preview", version = "0.1.0", features = ["debug", "display", "from", "try_into"] }
flume = "0.10.14"
futures = "0.3.25"
hex = { version = "0.4.3" }
iroh-io = { version = "0.2.1" }
iroh-net = { version = "0.5.1", path = "../iroh-net" }
iroh-bytes = { version = "0.5.0", path = "../iroh-bytes" }
iroh-metrics = { version = "0.5.0", path = "../iroh-metrics", optional = true }
num_cpus = { version = "1.15.0" }
portable-atomic = "1"
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"] }
quic-rpc = { version = "0.6", default-features = false, features = ["flume-transport"] }
quinn = "0.10"
range-collections = { version = "0.4.0" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["io-util", "rt"] }
tokio-util = { version = "0.7", features = ["io-util", "io"] }
tokio-stream = "0.1"
tracing = "0.1"
walkdir = "2"

# CLI
clap = { version = "4", features = ["derive"], optional = true }
config = { version = "0.13.1", default-features = false, features = ["toml", "preserve_order"], optional = true }
console = { version = "0.15.5", optional = true }
dirs-next = { version = "2.0.0", optional = true }
indicatif = { version = "0.17", features = ["tokio"], optional = true }
multibase = { version = "0.9.1", optional = true }
tempfile = { version = "3.4", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
data-encoding = "2.4.0"
url = { version = "2.4", features = ["serde"] }


[features]
default = ["cli", "metrics"]
cli = ["clap", "config", "console", "dirs-next", "indicatif", "multibase", "quic-rpc/quinn-transport", "tempfile", "tokio/rt-multi-thread", "tracing-subscriber"]
metrics = ["iroh-metrics", "flat-db", "mem-db", "iroh-collection"]
flat-db = []
mem-db = []
iroh-collection = []
test = []

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
blake3 = "1.3.3"
bytes = "1"
duct = "0.13.6"
nix = "0.26.2"
rand = "0.8"
regex = { version = "1.7.1", features = ["std"] }
testdir = "0.8"
tokio = { version = "1", features = ["macros", "io-util", "rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
iroh-io = { version = "0.2.1" }
postcard = "1"
proptest = "1.2.0"
tempfile = "3.4"
genawaiter = { version = "0.99", features = ["futures03"] }

[[bin]]
name = "iroh"
required-features = ["cli"]

[[example]]
name = "collection"
required-features = ["mem-db", "iroh-collection"]

[[example]]
name = "hello-world"
required-features = ["mem-db"]
