[package]
name = "iroh"
version = "0.7.0"
edition = "2021"
readme = "README.md"
description = "Bytes. Distributed."
license = "MIT OR Apache-2.0"
authors = ["dignifiedquire <me@dignifiedquire.com>", "n0 team"]
repository = "https://github.com/n0-computer/iroh"
default-run = "iroh"

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.70"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bao-tree = { version = "0.9.1", features = ["tokio_fsm"], default-features = false }
bytes = "1"
data-encoding = "2.4.0"
derive_more = { version = "1.0.0-beta.1", features = ["debug", "display", "from", "try_into"] }
flume = "0.10.14"
futures = "0.3.25"
genawaiter = { version = "0.99", default-features = false, features = ["futures03"] }
hex = { version = "0.4.3" }
iroh-bytes = { version = "0.7.0", path = "../iroh-bytes" }
iroh-io = { version = "0.3.0", features = ["stats"] }
iroh-metrics = { version = "0.7.0", path = "../iroh-metrics", optional = true }
iroh-net = { version = "0.7.0", path = "../iroh-net" }
itertools = "0.11.0"
num_cpus = { version = "1.15.0" }
portable-atomic = "1"
iroh-sync = { version = "0.7.0", path = "../iroh-sync" }
iroh-gossip = { version = "0.7.0", path = "../iroh-gossip" }
once_cell = "1.18.0"
parking_lot = "0.12.1"
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"] }
quic-rpc = { version = "0.6", default-features = false, features = ["flume-transport"] }
quinn = "0.10"
range-collections = { version = "0.4.0" }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
tempfile = "3.4"
tokio = { version = "1", features = ["io-util", "rt"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec", "io-util", "io", "time"] }
tracing = "0.1"
walkdir = "2"

# CLI
clap = { version = "4", features = ["derive"], optional = true }
comfy-table = { version = "7.0.1", optional = true }
config = { version = "0.13.1", default-features = false, features = ["toml", "preserve_order"], optional = true }
console = { version = "0.15.5", optional = true }
dialoguer = { version = "0.11.0", default-features = false, optional = true }
dirs-next = { version = "2.0.0", optional = true }
indicatif = { version = "0.17", features = ["tokio"], optional = true }
human-time = { version = "0.1.6", optional = true }
multibase = { version = "0.9.1", optional = true }
rustyline = { version = "12.0.0", optional = true }
shell-words = { version = "1.1.0", optional = true }
shellexpand = { version = "3.1.0", optional = true }
toml = { version = "0.7.3", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
url = { version = "2.4", features = ["serde"] }
colored = { version = "2.0.4", optional = true }

# Examples
ed25519-dalek = { version = "2.0.0", features = ["serde", "rand_core"], optional = true }

[features]
default = ["cli", "metrics"]
cli = ["clap", "config", "console", "dirs-next", "indicatif", "multibase", "quic-rpc/quinn-transport", "tokio/rt-multi-thread", "tracing-subscriber", "flat-db", "shell-words", "shellexpand", "rustyline", "colored", "toml", "human-time", "comfy-table", "dialoguer"]
metrics = ["iroh-metrics"]
flat-db = ["iroh-bytes/flat-db"]
test = []
example-sync = ["cli"]

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bytes = "1"
duct = "0.13.6"
genawaiter = { version = "0.99", features = ["futures03"] }
iroh-test = { path = "../iroh-test" }
nix = "0.26.2"
proptest = "1.2.0"
regex = { version = "1.7.1", features = ["std"] }
testdir = "0.8"
tokio = { version = "1", features = ["macros", "io-util", "rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[[bin]]
name = "iroh"
required-features = ["cli"]

[[example]]
name = "collection"
required-features = []

[[example]]
name = "dump-blob-stream"
required-features = []

[[example]]
name = "hello-world"
required-features = []

[[example]]
name = "sync"
required-features = ["example-sync"]

[[example]]
name = "rpc"
required-features = ["clap"]

[[example]]
name = "client"
required-features = ["cli"]
