[package]
name = "iroh-example-embed"
publish = false
version = "0.1.3"
edition = "2021"
authors = ["team@n0.computer"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Example of using iroh-embed"

[dependencies]
anyhow = "1"
futures-util = "0.3.21"
iroh-api = { path = "../../iroh-api" }
iroh-embed = { path = "../../iroh-embed" }
testdir = "0.7.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
