[package]
name = "iroh-store"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Implementation of the storage part of iroh"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ahash = "0.8.0"
async-trait = "0.1.56"
bytecheck = "0.6.7"
bytes = "1.1.0"
cid = "0.9"
clap = { version = "4.0.9", features = ["derive"] }
config = "0.13.1"
ctrlc = "3.2.2"
futures = "0.3.21"
git-version = "0.3.5"
iroh-metrics = { workspace = true, features=["store"] }
iroh-rpc-client.workspace = true
iroh-rpc-types.workspace = true
iroh-util.workspace = true
multihash = "0.17"
names = { version = "0.14.0", default-features = false }
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
rkyv = { version = "0.7.37", features = ["validation"] }
rocksdb = "0.19.0"
serde = { version = "1.0", features = ["derive"] }
smallvec = { version = "1.10.0", features = ["write"] }
tokio = { version = "1", features = ["rt"] }
tracing = "0.1.34"
tracing-opentelemetry = "0.18"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[dev-dependencies]
criterion = { version = "0.4.0", features = ["async_tokio"] }
libipld = "0.15.0"
rayon = "1.5.3"
tempfile = "3.3.0"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }

[[bench]]
name = "store"
harness = false

[[bench]]
name = "rpc"
harness = false
