[package]
name = "iroh-store"
version = "0.1.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "Implementation of the storage part of iroh"

[dependencies]
rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", branch = "master" }
anyhow = "1.0.57"
tokio = { version = "1.18.0", features = ["rt"] }
cid = "0.8.4"
rkyv = { version = "0.7.37", features = ["validation"] }
bytecheck = "0.6.7"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
clap = { version = "3.1.15", features = ["derive"] }
ctrlc = "3.2.2"
futures = "0.3.5"
tracing = "0.1.34"
iroh-rpc-types = { path = "../iroh-rpc-types" }
iroh-rpc-client = { path = "../iroh-rpc-client" }
iroh-util = { path = "../iroh-util" }
tonic = "0.7.2"
tonic-health = "0.6.0"
bytes = "1.1.0"
prometheus-client = "0.16.0"
iroh-metrics = { path = "../iroh-metrics" }
tracing-opentelemetry = "0.17.2"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
names = { version = "0.13.0", default-features = false }
git-version = "0.3.5"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
tempfile = "3.3.0"
tokio = { version = "1.18.0", features = ["rt", "macros", "rt-multi-thread"] }

[features]
default = []


[[bench]]
name = "store"
harness = false
