[package]
name = "iroh-qrpc-client"
version = "0.2.0"
edition = "2021"
authors = ["Friedel Ziegelmayer <me@dignifiedquire.com>", "ramfox"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/iroh"
description = "RPC type client for iroh"
rust-version = "1.63"

[dependencies]

anyhow = "1"
async-stream = "0.3.3"
bytes = "1.1.0"
cid = "0.9.0"
config = "0.13.1"
futures = "0.3.21"
iroh-metrics = { path = "../iroh-metrics", default-features = false }
iroh-util = { path = "../iroh-util" }
libp2p = { version = "0.50", default-features = false, features = ["gossipsub"] }
quic-rpc = { version = "0.2.1", features = ["http2"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
toml = "0.5.9"
tracing = "0.1.34"
iroh-qrpc-types = { path = "../iroh-qrpc-types" }
hyper = "0.14.23"

[dev-dependencies]
tokio-stream = { version = "0.1.9", features = ["net"] }
