[package]
name = "rocks-store"
version = "0.1.2"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Implementation of RocksDB based Store"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
flatfs-store = { path = "../flatfs", optional = true }
rocksdb = "0.19.0"

[dev-dependencies]
flatfs-store = { path = "../flatfs" }
tempfile = "3.3.0"

[features]
importer = ["flatfs-store"]
