[package]
name = "rocks-store"
version = "0.1.2"
edition.workspace = true
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license.workspace = true
repository.workspace = true
description = "Implementation of RocksDB based Store"
rust-version.workspace = true
publish = false

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
flatfs-store = { path = "../flatfs", optional = true }
rocksdb = "0.19.0"

[dev-dependencies]
flatfs-store = { path = "../flatfs" }
tempfile = "3.3.0"

[features]
importer = ["flatfs-store"]
