# Run tests using the beta Rust compiler

name: Beta Rust

on:
  schedule:
    # 06:50 UTC every Monday
    - cron: '50 6 * * 1'
  workflow_dispatch:
  # TODO: temporary to test in PR only
  pull_request:

concurrency:
  group: beta-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: './.github/workflows/tests.yaml'
    with:
      rust-version: beta
  notify:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract test results
        if: ${{ always() }}
        run: |
          printf '${{ toJSON(needs) }}\n'
          result=$(echo '${{ toJSON(needs) }}' | jq .tests.result | tr -d \")
          echo TESTS_RESULT=$result
          echo TESTS_RESULT=$result >>$GITHUB_ENV
      - run: |
          echo $TEST_RESULT
          echo ${{ env.TEST_RESULT == 'failure' }}
          echo ${{ env.TEST_RESULT != 'failure' }}
        if: ${{ always() }}
      - uses: n0-computer/discord-webhook-notify@v1
        if: ${{ always() && env.TEST_RESULT == 'failure' }}
        with:
          severity: error
          details: |
            rustc beta tests failed
            see https://github.com/n0-computer/iroh/actions/workflows/beta.yaml
          webhookUrl: ${{ secrets.DISCORD_N0_GITHUB_CHANNEL_WEBHOOK_URL }}

