# Run tests using the beta Rust compiler

name: Beta Rust

on:
  schedule:
    # 06:50 UTC every Monday
    - cron: '50 6 * * 1'
  workflow_dispatch:
  # TODO: temporary to test in PR only
  pull_request:

concurrency:
  group: beta-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: './.github/workflows/tests.yaml'
    with:
      rust-version: beta
  notify:
    needs: tests
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          printf '${{ toJSON(needs) }}\n'
          result=$(${{ toJSON(needs) }} | jq .tests.result | tr -d \")
          echo $result
      - uses: n0-computer/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          details: rustc beta tests failed
          webhookUrl: ${{ secrets.DISCORD_N0_GITHUB_CHANNEL_WEBHOOK_URL }}
      # TODO: temporarily to test the notification
      - uses: n0-computer/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          details: rustc beta tests succeeded
          webhookUrl: ${{ secrets.DISCORD_N0_GITHUB_CHANNEL_WEBHOOK_URL }}

