name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: -Dwarnings
  MSRV: "1.65"

jobs:
  cross:
    name: Cross compile
    runs-on: [self-hosted, linux, X64]
    strategy:
      fail-fast: false
      matrix:
        target:
          - i686-unknown-linux-gnu
          - armv7-linux-androideabi
          - aarch64-linux-android

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Install rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Cleanup Docker
      continue-on-error: true
      run: |
        docker kill $(docker ps -q)

    - name: Install cross
      # See https://github.com/cross-rs/cross/issues/1222
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: check
      run: cross check --all --target ${{ matrix.target }}

    - name: test
      run: cross test --all --target ${{ matrix.target }} -- --test-threads=12
