name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [nightly, stable]
        experimental: [false]
        include:
          - os: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache
            release-os: linux
            release-arch: amd64
          - os: macos-latest
            sccache-path: /Users/runner/Library/Caches/Mozilla.sccache
            release-os: darwin
            release-arch: x86_64
          - os: windows-latest
            rust: stable
            sccache-path: "%LOCALAPPDATA%\\sccache"
            release-os: windows
            release-arch: amd64
            experimental: true
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      RUSTV: ${{ matrix.rust }}
      SCCACHE_CACHE_SIZE: 2G
      # SCCACHE_RECACHE: 1 # Uncomment this to clear cache, then comment it back out
    steps:
    - uses: actions/checkout@master

    - name: Set sccache env path
      if: matrix.os != 'windows-latest'
      run: |
          echo "SCCACHE_DIR=${{ matrix.sccache-path }}" >> $GITHUB_ENV
    - name: Set build arch
      run: |
        echo "RELEASE_ARCH=${{ matrix.release-arch }}" >> $GITHUB_ENV
        echo "RELEASE_OS=${{ matrix.release-os }}" >> $GITHUB_ENV
    
    - name: Install sccache (ubuntu-latest)
      if: matrix.os == 'ubuntu-latest'
      env:
        LINK: https://github.com/mozilla/sccache/releases/download
        SCCACHE_VERSION: v0.2.15
      run: |
        SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        chmod 755 $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH  
    
    - name: Install scoop (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\\install.ps1 -RunAsAdmin
        Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
    
    - name: Install sccache (windows-latest)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: scoop install sccache
    
    - name: Install sccache (macos-latest)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install sccache          
    
    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    
    - name: Cache cargo registry
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: |
          ~/.cargo/registry          
          ~/.cargo/bin
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ./target
            
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
                      ${{ runner.os }}-${{ matrix.rust }}-cargo-
    - name: Save sccache
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: ${{ matrix.sccache-path }}
        key: ${{ runner.os }}-${{ matrix.rust }}-sccache-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
                      ${{ runner.os }}-${{ matrix.rust }}-sccache-
    - name: Start sccache server
      run: sccache --start-server

    - name: Install Protoc windows
      if: matrix.os == 'windows-latest'
      uses: arduino/setup-protoc@v1

    - name: Install Protoc linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        PROTOC_VERSION=3.20.1
        PROTOC_ZIP=protoc-$PROTOC_VERSION-linux-x86_64.zip
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP
        sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
        sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
        rm -f $PROTOC_ZIP
        echo "PROTOC=/usr/local/bin/protoc" >> $GITHUB_ENV
        echo "PROTOC_INCLUDE=/usr/local/include" >> $GITHUB_ENV
    
    - name: Install Protoc macOS
      if: matrix.os == 'macOS-latest'
      run: |
        PROTOC_VERSION=3.20.1
        PROTOC_ZIP=protoc-$PROTOC_VERSION-osx-x86_64.zip
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$PROTOC_ZIP
        sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
        sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
        rm -f $PROTOC_ZIP
        echo "PROTOC=/usr/local/bin/protoc" >> $GITHUB_ENV
        echo "PROTOC_INCLUDE=/usr/local/include" >> $GITHUB_ENV

    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --bins --tests --examples

    - name: check bench
      uses: actions-rs/cargo@v1
      if: matrix.rust == 'nightly'
      with:
        command:  check
        args: --benches

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all

    - name: clipy
      uses: actions-rs/cargo@v1
      if: matrix.os == 'ubuntu-latest' && matrix.rust=='stable'
      with:
          command: clippy
          args: --all --tests --benches -- -D warnings

    - name: build release
      uses: actions-rs/cargo@v1
      if: matrix.os != 'windows-latest' && matrix.rust=='stable'
      # && github.ref_name=='main'
      with:
        command: build
        args: --release
    
    - name: Get current iroh-gateway version
      id: ig_version
      if: matrix.os != 'windows-latest' && matrix.rust=='stable'
      # && github.ref_name=='main'
      uses: dante-signal31/rust-app-version@v1.0.0
      with:
         cargo_toml_folder: iroh-gateway/
    
    - name: Get current iroh-p2p version
      id: ip2p_version
      if: matrix.os != 'windows-latest' && matrix.rust=='stable'
      # && github.ref_name=='main'
      uses: dante-signal31/rust-app-version@v1.0.0
      with:
         cargo_toml_folder: iroh-p2p/
    
    - name: Get current iroh-store version
      id: istore_version
      if: matrix.os != 'windows-latest' && matrix.rust=='stable'
      # && github.ref_name=='main'
      uses: dante-signal31/rust-app-version@v1.0.0
      with:
         cargo_toml_folder: iroh-store/

    - name: Setup awscli on mac
      if: matrix.os == 'macos-latest' && matrix.rust=='stable'
      # && github.ref_name=='main'
      run: |
        curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
        sudo installer -pkg AWSCLIV2.pkg -target /

    - name: Setup awscli on linux
      if: matrix.os == 'ubuntu-latest' && matrix.rust=='stable'
      # && github.ref_name=='main'
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Set aws credentials
      if: matrix.os != 'windows-latest'
      run: |
          echo "AWS_ACCESS_KEY_ID=${{secrets.S3_ACCESS_KEY_ID}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{secrets.S3_ACCESS_KEY}}" >> $GITHUB_ENV

    - name: push release
      if: matrix.os != 'windows-latest' && matrix.rust=='stable' 
      #&& github.ref_name=='main'
      run: |
        aws s3 cp ./target/release/iroh-gateway s3://vorc/iroh-gateway-${RELEASE_OS}-${RELEASE_ARCH}-${{ steps.ig_version.outputs.app_version }}-${GITHUB_SHA::7} --no-progress
        aws s3 cp ./target/release/iroh-p2p s3://vorc/iroh-p2p-${RELEASE_OS}-${RELEASE_ARCH}-${{ steps.ip2p_version.outputs.app_version }}-${GITHUB_SHA::7} --no-progress
        aws s3 cp ./target/release/iroh-store s3://vorc/iroh-store-${RELEASE_OS}-${RELEASE_ARCH}-${{ steps.istore_version.outputs.app_version }}-${GITHUB_SHA::7} --no-progress

    - name: push release latest
      if: matrix.os != 'windows-latest' && matrix.rust=='stable'
      # && github.ref_name=='main'
      run: |
        aws s3 cp ./target/release/iroh-gateway s3://vorc/iroh-gateway-${RELEASE_OS}-${RELEASE_ARCH}-latest --no-progress
        aws s3 cp ./target/release/iroh-p2p s3://vorc/iroh-p2p-${RELEASE_OS}-${RELEASE_ARCH}-latest --no-progress
        aws s3 cp ./target/release/iroh-store s3://vorc/iroh-store-${RELEASE_OS}-${RELEASE_ARCH}-latest --no-progress
    
    - name: Print sccache stats
      run: sccache --show-stats
    - name: Stop sccache server
      run: sccache --stop-server || true

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check